version: '3.8'

# Configuracion de desarrollo local con recarga en caliente (nodemon)
services:
  gateway:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  bff-punto-venta:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/bff-punto-venta:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  bff-auditoria:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/bff-auditoria:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  evaluacion-core:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/evaluacion-core:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  buro-simulado:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/buro-simulado:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  repositorio-interno:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/repositorio-interno:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  auditoria:
    build:
      args:
        INSTALL_DEV: "true"
    command: npm run dev
    volumes:
      - ./services/auditoria:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
